### ISSUE TITLE
关于 groupby_parallel

### ISSUE THREAD

**Issue by langzi00** [SeafyLiang/Python_study#1]
def grouped_data_diff(x,name):
    
    # process
    return  x.diff().fillna(0)
 
def applyParalleldata(dfGrouped, func):
    res = Parallel(n_jobs=60)(delayed(func)(group,name) for name,group in dfGrouped)
    return pd.concat(res)

price_ask_level_df_diff = applyParalleldata(price_ask_level_df.groupby(['instrumentid','date'])[zero_up_to_nine[:-2]], grouped_data_diff)

我也像您一样使用了groupby操作， parallel 函数相同，但是始终提示  TypeError: unsupported operand type(s) for -: 'str' and 'str'

想问问您这个x，在并行groupby中到底是啥用法

**Comment by SeafyLiang** [comment]
这里的x是pandas的切片，如果x中有某列的话，可以改成
`x['col'].diff().fillna(0)`
试一下。

此块内容为pandas使用groupby并行加速，使用了joblib中的Parallel函数，这个函数其实是进行并行调用的函数，其中的参数n_jobs是使用的计算机核的数目，后面其实是使用了groupby返回的迭代器中的group部分，也就是pandas的切片，然后依次送入func这个函数中。
具体例子可参考一下这个博客：https://blog.csdn.net/qtlyx/article/details/87301224
